[package]
name = "tests"
version = "0.1.0"
edition = "2021"

[dependencies]
flat_message = { path = "../flat_message" }
smallvec = { version = "1.15.1", optional = true }
yoke = { version = "0.8.1", features = ["derive"], optional = true }

[lints]
workspace = true

[features]
smallvec = ["dep:smallvec", "flat_message/smallvec"]
stable_deref = ["flat_message/stable_deref", "yoke"]
