[package]
name = "flat_message"
version = "0.1.0"
edition = "2021"
authors = ["Gavrilut Dragos <gavrilut.dragos@gmail.com>", "Andrei Damian <andreidaamian@gmail.com>"]
description = "Zero-copy, schema-less serialization and deserialization fast library for Rust."
license = "MIT"
repository = "https://github.com/gdt050579/FlatMessage"
readme = "../README.md"
documentation = "https://docs.rs/flat_message"
keywords = ["serialization", "deserialize", "serialize", "zero-copy", "schema-less"]
categories = ["encoding"]

[dependencies]
# flat_message_proc_macro = { path = "../flat_message_proc_macro" }
flat_message_proc_macro = "0.1.0"
serde = { version = "1", optional = true }
crc32fast = "1"

[features]
default = []
check_crc32 = []
benchmarks = ["dep:serde"]

[lints]
workspace = true


